# Generated by Django 3.2.6 on 2021-08-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reginout', '0002_account_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
